### ISSUE TITLE
when using small_truck_access the getUsedCategories method returns truck_access too it seems

### ISSUE THREAD

**Issue by karussell** [graphhopper/custom-model-editor#2]
I tested the RoadsTagParser with the RHS expression and used something like

```
{
  "speed": [{
          "if": "true",
          "limit_to": "small_truck_average_speed"
        }, {        
          "else_if": "small_truck_access==false && something",
          "multiply_by": "0"
        }, { ... }
  ]
}
```

as the custom_model but the request failed with 

You requested the details
[road_class, small_truck_access, truck_access, average_speed, distance, time] but we could only find
[road_class, small_truck_access, average_speed, distance, time]

Probably the RHS stuff is unrelated and the problem is that we do no longer contain the `$` in these encoded value? Before it was `small_truck$average_speed` and `small_truck$access`.

In production I will include a hack so that I can continue using it for this special case :) (so test this only on a local instance please )

**Comment by easbar** [comment]
Yes this is a bug:

https://github.com/graphhopper/custom-model-editor/blob/693a44097271ed84f603f46efbfcfc56ab97b608/src/custom_model_editor.js#L116-L120

We add every category that appears in the condition to the 'used categories'. So when we use `small_truck_access` we add `small_truck_access` **and** `truck_access` as well.
