### ISSUE TITLE
backward variable and ! operator

### ISSUE THREAD

**Issue by karussell** [graphhopper/custom-model-editor#6]
It would be nice to have a negation alternative to `xy == false`, i.e. `!xy`.

Plus support for [backward_xy](https://github.com/graphhopper/graphhopper/pull/2760).

**Comment by easbar** [comment]
I think for backward_xy, all you need to do is add them to the list of encoded values here: 

https://github.com/graphhopper/graphhopper-maps/blob/be469082076e09824f0105f9e27532824917e476/src/sidebar/CustomModelBox.tsx#L18-L32

I'll take a look at the negation operator.

**Comment by karussell** [comment]
Nice, thank you!
